### ISSUE TITLE
Possible toggle for the Tyrael and Diablo(?) artwork over orbs (Feature req.)

### ISSUE THREAD

**Issue by Sottises** [cogwerkz/DiabolicUI#108]
**Description**
In a proposed options menu, introduce a toggle for the artwork over the orbs to reduce "clutter" on screen if desired. This is of minor importance if at all possible (is the artwork a seperate layer to the actionbar frame and the orbs?)

**Version Number**
1.3.103-Release

**Comment by goldpaw** [comment]
Well I'm working on a separate addon for just showing orbs and artwork. But in this UI, I don't plan on implementing any choices. Because it just doesn't look that good underneath. I haven't made the backdrops and overlays in such a manner that they really be shown on their own. It's a full package!
