### ISSUE TITLE
Alternative Stance/Druid Forms bar

### ISSUE THREAD

**Issue by AntonyMcLovin** [cogwerkz/DiabolicUI#14]
Hi there, 

I play a Druid healer so I have that "+" icon, where I have to click to see all different shapeshift forms I can use. Is it also possible to not show one "+" icon but all forms next to each other?
In pvp we dont have time to click twice so I have to put all the different forms also in the main bar to be more reactive. :)

**Comment by goldpaw** [comment]
In PvP I personally have all my forms keybound and using macros, so that's probably why I always just try to get the shapeshift bar out of the way. But yes, the position and system on the current 1.0 live version is baaaad! :D  

In 1.1 it'll be moved more to the side, which of course doesn't solve the problem. So I will put it on my list to make it an option to show the entire bar, above the normal action bar like in the default UI. :)
