### ISSUE TITLE
Health globe does not work for warlock (zhTW client)

### ISSUE THREAD

**Issue by class2u** [cogwerkz/DiabolicUI#27]
Thank you for making this addon. Amazing great job! 

There is one issue. Health globe does not work for warlock. It is grey and does not change while been damaged. Mana globe is blue but does not change neither. For other classes, I tested with druid, monk and paladin, they works fine.

I am using 1.1.26-release and Traditional Chinese zh-TW client.

**Comment by goldpaw** [comment]
I'm not able to reproduce this, at least not here. It's working fine on warlocks I've tested on both the blizzard and private realms. So I'm thinking this might be differences with the Chinese WoW client, since I know quite a few things are different there. Like skeletons have skin, piles of bones in the world aren't there and so on. So it might be some different things in the addon API too. 

Can you do me a favor and type the following in-game if possible, and then post a screenshot of the result? It's supposed to print a list of the class name in English, and in capital letters. This is how we identify classes in addons. If something is different there, that's what I need to change. :) 

```Lua
/run for c in pairs(RAID_CLASS_COLORS) do print(c) end
``` 

I'll keep searching for any info on my own regardless of the result, though. We'll figure it out! :)
