### ISSUE TITLE
special ability action bar (hotfix re-moved with new version to bottom left again?)

### ISSUE THREAD

**Issue by AntonyMcLovin** [cogwerkz/DiabolicUI#35]
Hi there, 

I commented on this before which was then hotfixed. With the newest Version of Diabolic UI the special boss / quest action bar was again removed to the bottom left: see Screenshot: 

https://picload.org/image/rlaacwrw/unbenannt.png

Is there a way to get the place removed again? Its too far away for pve ;)

thx in advance ;)

**Comment by AntonyMcLovin** [comment]
hotfixed with 1.1.31

**Comment by goldpaw** [comment]
No, I haven't hotfixed anything, actually. If that's the ExtraActionButton1, I haven't done anything to it since July 11th 2016. 

The next time it bugs out, which I assume it will, can you do a /framestack in-game, holde the mouse over it and screenshot it? I just need to see the name of the button, so I know where I can start to fix it. :)

**Comment by AntonyMcLovin** [comment]
you are right, bugs out quite often ;)
here you go: https://picload.org/image/rlogpcdw/unbenannt.png

**Comment by goldpaw** [comment]
It appears to be styled along with the rest of the UI, though. I think I can see where the bug is. It's position relative to the bottom left corner is about what it should be relative to the power orb. 

I'll get it fixed. :)

**Comment by AntonyMcLovin** [comment]
Awesome! Thanks :)
