### ISSUE TITLE
grey spells when flying but able to cast spells

### ISSUE THREAD

**Issue by AntonyMcLovin** [cogwerkz/DiabolicUI#45]
Hi there, 

I did the Kaelthas 5 Man dungeon today and at the end Kaelthas casts a spell where all characters are flying. My spells all went grey, like when I'm mounted and at the air. But at the fight I'm able to cast spells. so the grey should be removed at situations like this... If possible, I mean.

**Comment by goldpaw** [comment]
The gray color was intentional, but I actually never thought about fights where we're flying. Which is something that's been around since WotLK, so I should have. 

I'll add something that makes the bars have their normal (or real, actually) colors when we're in combat or instances, even if we're flying. That should fix the problem. :)
