### ISSUE TITLE
Missing Buffs/Debuffs/Objective Tracker

### ISSUE THREAD

**Issue by gespi8** [cogwerkz/DiabolicUI#66]
**Description**

The player buffs and debuffs are absent from my UI. The objectives window that's normally under the minimap is missing. They didn't disappear. Neither elements were present when I first installed the addon.

**Version Number**

1.2.58

**Only DiabolicUI Enabled**

The issue still exists when DiabolicUI is the only addon enabled. 

**Additional Information**

The issue was present on both computers that I downloaded the addon to. I've tried reinstalling the addon a few times.

**Comment by dualcoding** [comment]
User here; haven't had this problem with git master which should be similar. I'll try to confirm with your specific version later!

Have you used a previous version of the addon? If so, it might be worth a shot to delete settings saved to your account in WTF/Account/<account number>/SavedVariables/DiabolicUI.lua

**Comment by gespi8** [comment]
I'll try this now thank you!

**Comment by dualcoding** [comment]
Unless something weird happens because of an error elsewhere, that code is there to help support various monitor layouts and resolutions and such. I am assuming it for some reason fails to get your screen resolution from the game client.

I'm not very familiar with the code, so it's probably best to wait for @goldpaw to get a proper solution. Posting the number of monitors you have and their resolution would be helpful though!

If you feel adventurous, I put up a branch with debugging prints and (possibly) a temporary solution here: https://github.com/dualcoding/DiabolicUI/tree/debugging

**Comment by dualcoding** [comment]
If you copy-paste this in the chat window, the output would likely be useful as well: "/run print(GetCurrentResolution(), GetScreenResolutions(), GetCVar("gxMonitor"))" (without quotes)
What this does is ask WoW to print the currently selected resolution number, the list of available resolutions, and (I think) the monitor index that the game is running on.

**Comment by goldpaw** [comment]
Never seen that code create a nil bug before, but I assume my aura module requests the information about pixel sizes too early in the loading process, and thus causing the bug for some. I'll look into it! 

Having that said, that code is there to help with those using triple monitor setups in WoW. WoW doesn't support this, so it'll stretch the UI out across all the 3 screens. That script keeps the UI on the center screen instead, like everybody in their right mind would want it to! :D 

The bug is unintentional, though. ;)

**Comment by goldpaw** [comment]
This will be fixed in the upcoming 1.3 release.

**Comment by gespi8** [comment]
After reading your comments about the resolution messages, I switched both computers to _Windowed Fullscreen_ instead of Windowed and the buffs/objectives appeared. Thank you very much.
