### ISSUE TITLE
Diabolic UI conflicts with other addons

### ISSUE THREAD

**Issue by Luellin** [cogwerkz/DiabolicUI#83]
**Description**
Hi, i'm having some sound issues wiht other addons only when diabolic ui is active, for example Wholly and classic quest log addon, this is the answer they gave me:

The latest version of Wholly will play the sound using the following:

PlaySound(PlaySoundKitID and "igCharacterInfoOpen" or 839);

Note that this is done to handle the situation where Wholly is running in an older environment or the newer one where the sounds need to be numbers.  I would imagine that your custom UI is defining PlaySoundKitID which is causing the problem.  I would suggest you contact them to tell them that if they are setting up a value for this in the global space they are causing problems in other addons.  PlaySoundKitID is something Blizzard controls.

**Version Number**
1.3.70

**Steps to Reproduce**
For classic quest log
1. Install
2. and press "L" to open the quest log
For wholly requires the grail database
1. install both
2. Type /wholly

**Only DiabolicUI Enabled**
Yes keep getting the errors

**Comment by goldpaw** [comment]
I'd say the problem here is that wholly makes assumptions based on he existance of a global command or not, while they should be checking for either client build version or existence of the SOUNDKIT table instead. Because PlaySoundKitID is NOT something Blizzard controls in 7.3.0.  

I've posted some suggested fixes for them in your closed bug report over at Curseforge, so hopefully they'll take a look at those and include them. :)

**Comment by goldpaw** [comment]
DiabolicUI does this differently now, and should be compatible with all Ace3-based addons, and all those that use the same bad method as Ace3.
